# 딥러닝및실습-1차-김주상-2020136031

In [1]:
import torch
import numpy as np

# a_tensor_initialization

+ 기술적 사항
    + torch.tensor를 통해 다양한 차원의 Tensor 생성 가능
    + dtype, device, requires_grad, size(), shape 등 속성이 있음
+ 기술적 고찰
    + Tensor를 생성할때 각 차원별 원소 개수가 동일해야함

In [2]:
# torch.Tensor class
# 텐서 만들고 설정된 값 출력함
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
t1_cpu = t1.cpu()

In [4]:
# tensor 함수로 텐서 생성하고 설정된 값 출력함
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [5]:
t2_cpu = t2.cpu()

In [6]:
# 텐서 만들고 shape으로 차원 출력함.
# 여기서 만든 텐서는 그냥 숫자라 차원이 0임(스칼라 텐서라 함)
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

torch.Size([]) 0


In [7]:
# 리스트에 담아서 위와 달리 1차원 텐서임
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [8]:
# 원소 5개 들어있어 길이 5인 1차원 텐서임
a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [9]:
# 2차원 텐서임(5행 1열)
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [10]:
# 2차원 텐서임(3행 2열)
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [11]:
# 3차원 텐서임(3 * 2 * 1)
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [12]:
# 4차원 텐서임(3 * 1 * 2 * 1)
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [13]:
# 4차원 텐서임(3 * 1 * 2 * 3)
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [14]:
# 4차원 텐서임(3 * 1 * 2 * 3 * 1)
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [15]:
# 위는 2차, 아래는 3차임
# 동일한 형태여도 []에 따라서 차원이 결정됨
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


In [16]:
# [1,2,3]과 [4,5]의 길이가 달라서 생성 불가
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

# b_tensor_initalization_copy

+ 기술적 사항
    + torch.Tensor(data) : float, 원본과 독립
    + torch.tensor(data) : int, 원본과 독립
    + torch.as_tensor(data) : int, 원본과 메모리 공유(list x)
+ 기술적 고찰
    + as_tensor는 메모리를 새로 생성하는 것이 아닌 기존 것을 재활용하니 메모리 절약이 가능할 것 같다.
    + 하지만 원본 데이터와 독립성이 있는 tensor가 안정성에 있어서 좋을 것 같다.

In [ ]:
# 텐서를 3개 생성함

# t1은 Tensor(대문자)로 생성함
# 리스트와 연동 x -> 리스트를 바꿔도 텐서는 영향 x
# float형이라 출력하면 소수점 있음
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

# t2은 Tensor(소문자)로 생성함
# 리스트와 연동 x -> 리스트를 바꿔도 텐서는 영향 x
# int형이라 출력하면 소수점 있음
l2 = [1, 2, 3]
t2 = torch.tensor(l2)

# t3은 as_tensor로 생성함
# 리스트와 연동 o -> 리스트를 바꿔도 텐서는 영향 o
# 근데 여기서는 그냥 list사용해서 연동 x
# int형이라 출력하면 소수점 있음
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [ ]:
# 위와 달리 np.array를 사용
# t4, t5는 연동되지 않기 때문에 변화 x
# t6은 t3과 달리 np.array가 바뀌면 텐서도 바뀜
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


In [ ]:
### 추가 코드 ###
# 차원 변경도 가능할까? -> 불가능
l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l6 = l6.reshape(3, 1)
print(l6, t6)
l6 = np.array([[1, 2, 3]])
print(l6, t6)

[[100]
 [  2]
 [  3]] tensor([100,   2,   3])
[[1 2 3]] tensor([100,   2,   3])


In [ ]:
### 추가 코드 ###
# 값 추가도 가능할까? -> 가능
l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

np.append(l6, 4)

array([1, 2, 3, 4])

# c_tensor_initialization_constant_values

+ 기술적 사항
    + torch.ones : 모든 원소가 1인 Tensor
    + torch.zeros : 모든 원소가 0인 Tensor
    + torch.empty : 값이 초기화 되지 않은 Tensor
    + torch.ones_like : 입력 Tensor와 같은 설정을 갖는 1로 채워진 Tensor
    + torch.zeros_like : 입력 Tensor와 같은 설정을 갖는 0으로 채워진 Tensor
    + torch.empty_like : 입력 Tensor와 같은 설정을 갖는 초기화 되지 않은 Tensor
    + torch.eye(n) : n*n I생성
+ 기술적 고찰
    + _like는 shape, dtype, device와 같은 설정값들을 맞춰줘서 안정적인것 같다.
    + empty는 값이 랜덤으로 채워져서 학습완료후 초기화시 사용하면 좋을 것 같다.

In [ ]:
# .ones : 1.로 채워진 텐서 생성
# .ones_like : input모양의 1.로 채워진 텐서 생성
t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([ 0.0000,  1.8750,  3.0000, 25.0000])
tensor([1.0000,    nan, 0.9196, 0.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# .zeros : 0.로 채워진 텐서 생성
# .zeros_like : input모양의 0.로 채워진 텐서 생성
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

In [ ]:
### 추가 코드 ###
# ones와 ones_like의 차이는 무엇?
# ones는 기본값으로 설정되지만, like는 모든 설정값을 가져옴
t1 = torch.ones(3, dtype=torch.float64, device='cpu', requires_grad=True)

# ones
t2 = torch.ones(t1.shape)
print(t2.dtype, t2.device, t2.requires_grad)
# >>> torch.float32 cpu False

# ones_like
t3 = torch.ones_like(t1)
print(t3.dtype, t3.device, t3.requires_grad)
# >>> torch.float64 cpu True

torch.float32 cpu False
torch.float64 cpu False


In [ ]:
# .empty : 메모리만 할당함 값은 메모리에 남아있던 값 그대로
# .empty_like : input모양으로 메모리만 할당함
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

In [ ]:
# n*n 단위 행렬(I) 생성
# 단위 행렬은 행렬 연산에서 항등원 역할임 ( A * I = A )
t4 = torch.eye(n=3)
print(t4)

# d_tensor_initialization_random_values

+ 기술적 사항
    + torch.randint(low, high, size) : 지정 범위 내 정수 난수 Tensor
    + torch.rand(size) : [0,1) 균등분포 난수 Tensor
    + torch.randn(size) : 평균 0, 표준편차 1 정규분포 난수 Tensor
    + torch.normal(mean, std, size) : 평균/표준편차 지정 정규분포 난수 Tensor
    + torch.linspace(start, end, steps) : start~end 균등 간격 Tensor
    + torch.arange(end) : 0~end-1 범위 정수 Tensor
    + torch.manual_seed(seed) : 난수 시드 고정
+ 기술적 고찰
    + linspace와 arange는 수열 생성이 직관적이라 for문으로 반복시 잘 사용될 것 같다.
    + 시드를 고정하면 랜덤한 난수 생성이 항상 동일하게 나오므로 실험 재현에 도움이 될 것 같다.


In [ ]:
# randint : 10~19 랜덤 생성(정수)
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[13, 18]])


In [ ]:
# rand : 0~1 랜덤 생성
t2 = torch.rand(size=(1, 3))
print(t2)

tensor([[0.8250, 0.0266, 0.5221]])


In [ ]:
# randn : 평균 0, 표준편차 1 정규분포 형태로 랜덤 생성
t3 = torch.randn(size=(1, 3))
print(t3)

tensor([[-0.0482, -0.4358, -0.5361]])


In [ ]:
# normal : 평균, 표준편차 설정하여 정규분포 랜덤 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[11.0086, 10.7314],
        [ 9.9443, 10.9034],
        [11.6362, 10.6152]])


In [ ]:
# linspace : start~end까지 지정한 step 수만큼 균일하게 나눈 연속값 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [ ]:
# arange(n) : 0, 1, 2, ... , n-1 배열 생성
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


In [ ]:
# manual_seed : 시드 고정
# 시드 고정하면 랜덤 생성 결과가 항상 동일하게 나옴
# 시드 고정 후 random1 = random3 , random2 = random4
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)
random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)
random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

+ 기술적 사항
    + Tensor 생성 시 dtype 지정 가능 (예: torch.ones((2,3), dtype=torch.int16))
    + 기본 생성 Tensor dtype은 float32
    + Tensor 타입 변환: .to(dtype), .double(), .short(), .type(torch.타입)
    + 연산 시 dtype 규칙: 서로 다른 dtype Tensor 연산 → 결과 dtype은 업캐스팅 규칙에 따라 결정
+ 기술적 고찰
    + 필요한 정밀도나 메모리 효율에 따라 적절한 dtype을 선택하면 좋을 것 같다.
    + 타입 에러 방지를 위해 연산 전후 dtype이 어떤 규칙으로 정해지는지 잘 알아야 할것 같다. 

In [ ]:
# 2 * 3 텐서 만들고 데이터 타입 확인(디폴트값 : float32)
a = torch.ones((2, 3))
print(a.dtype)

torch.float32


In [ ]:
# 2 * 3 텐서를 int16 타입으로 생성
b = torch.ones((2, 3), dtype=torch.int16)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [ ]:
# 2 * 3 랜덤 실수 텐서를 float64 타입으로 생성 후 20곱함
# 20 곱하면 0~1 랜덤 값이 0~20 랜덤 값으로 변함
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)


In [ ]:
# b 텐서를 int32 타입으로 변환
d = b.to(torch.int32)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [ ]:
# double 타입과 short 타입 텐서 생성
# 다음 4가지 방법으로 생성 가능
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [ ]:
# double 타입과 short타입을 곱함
# 곱셈시 결과는 더 많은 값을 표현할 수 있는 타입으로 변환됨(데이터 손실 방지)
# double > short -> torch.float64
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


# f_tensor_operations

+ 기술적 사항
    + Tensor 연산은 함수(torch.add, torch.sub, torch.mul, torch.div)와 연산자(+, -, *, /) 모두 동일하게 작용

+ 기술적 고찰
    + 함수와 연산자를 둘 다 사용할 수 있어서 좋다.
    + 연산 결과는 항상 새로운 Tensor가 생성되므로 기존 Tensor를 보존하면서 계산할 수 있을 것 같다.

In [ ]:
# 텐서 덧셈 예시
# torch.add()와 + 는 동일한 연산 수행함
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [ ]:
# 텐서 뺄셈 예시
# torch.sub()와 - 는 동일한 연산 수행함
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 텐서 곱셈 예시
# torch.mul()와 * 는 동일한 연산 수행함
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# 텐서 나눗셈 예시
# torch.div()와 / 는 동일한 연산 수행함
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm

+ 기술적 사항
    + torch.dot(a, b) : 1차원 Tensor 간 내적(dot product)
    + torch.mm(a, b) : 2차원 Tensor 행렬 곱(matrix multiplication)
    + torch.bmm(a, b) : 3차원 Tensor 배치 행렬 곱(batch matrix multiplication)
+ 기술적 고찰
    + 내적, 행렬 곱, 배치 행렬 곱을 잘 구분 해야할 것 같다.
    + bmm을 활용하면 한번에 행렬 연산을 처리할 수 있어서 시간을 단축할 수 있다(for문 보다 빠름).

In [ ]:
# 1차원 벡터 내적(dot)
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

tensor(7) torch.Size([])


In [ ]:
# (2 * 3)와 (3 * 2) 행렬 곱셈(mm)
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


In [ ]:
### 추가 코드 ###
# (a * x) (x * b) 형태여야함 아니면 에러남
t2 = torch.randn(2, 3)
t3 = torch.randn(2, 4)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x4)

In [ ]:
# (10 * 3 * 4)와 (10 * 4 * 5) 행렬 곱셈(bmm)
# (x * a * y) (x * y * b) 형태여야함
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

torch.Size([10, 3, 5])


# h_tensor_operations_matmul

+ 기술적 사항
    + torch.matmul(a, b) : 다양한 차원 Tensor 곱을 통합 지원
        + 1D x 1D → dot product (스칼라)
        + 2D x 1D → 행렬 x 벡터 (matmul)
        + 3D x 1D → 배치 행렬 x 벡터 (matmul)
        + 3D x 3D → 배치 행렬 곱 (bmm사용)
        + 3D x 2D → 배치 행렬 x 단일 행렬 (matmul)
+ 기술적 고찰
    + torch.matmul을 사용하면 mm, bmm으로는 불가능한 다양한 차원의 곱셈을 처리할 수 있다.
    + 배치 연산을 지원해주니 신경망에서 여러개를 동시에 계산할 수 있을 것 같다.


In [ ]:
# 벡터 * 벡터: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

torch.Size([])


In [ ]:
# 행렬 * 벡터: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

torch.Size([3])


In [ ]:
# 배치 행렬 * 벡터: baroadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

torch.Size([10, 3])


In [ ]:
# 배치 행렬 * 배치 행렬: bmm  
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [ ]:
# 배치 행렬 * 일반 행렬: broadcasted dot
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])


In [ ]:
### 추가 코드 ###
# 여기서 사용한 matuml은 뭘까?
# mm또는 dmm은 각각 2차*2차, 3차*3차 전용이라 3차*2차 행렬곱이 불가능함
a = torch.randn(10, 3, 4)
b = torch.randn(4, 5)
print(torch.bmm(a, b).size())

RuntimeError: batch2 must be a 3D tensor

In [ ]:
### 추가 코드 ###
# matmul은 선형대수적 텐서 곱셈 수행 -> 3차 * 2차 가능
a = torch.randn(10, 3, 4)
b = torch.randn(4, 5)
print(torch.matmul(a, b).size())

In [ ]:
### 추가 코드 ###
# 설정만 해준다면 4차 * 4차도 가능
a = torch.ones(2, 3, 4, 5)
b = torch.randn(2, 3, 4, 5)
c = torch.matmul(a, b.transpose(-1, -2))
print(c.size())

torch.Size([2, 3, 4, 4])


# i_tensor_broadcasting

+ 기술적 사항
    + Tensor와 스칼라 연산 가능: +, -, *, / 및 add, sub, mul, div 함수 사용 가능
    + normalize : Tensor 전체를 n으로 나누어 정규화 가능
    + 브로드캐스팅(Broadcasting) 지원: 서로 다른 차원의 Tensor도 연산 가능
    + pow 연산: torch.pow(Tensor, n)으로 각 원소별 거듭제곱 가능
+ 기술적 고찰
    + 브로드캐스팅 덕분에 복잡한 차원 Tensor도 간단히 연산할 수 있을 것 같다.
    + Tensor 연산시 브로드캐스팅에 필요한 규칙들을 만족하게 해야겠다.
    + normalize처럼 스칼라 연산을 통해 데이터 전처리를 직관적으로 처리할 수 있을 것 같다.
    + pow 연산을 활용하면 각 원소별 계산을 간결하게 수행할 수 있을 것 같다.


In [ ]:
# 벡터 * 스칼라 -> 각 원소에 스칼라 곱
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

tensor([2., 4., 6.])


In [ ]:
# (3 * 2) - (2) -> 각 행마다 t4값 빼기
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [ ]:
# 스칼라 연산 테스트(+, -, *, /)
# + : 각 원소에 스칼라 값 더함
# - : 각 원소에 스칼라 값 뺌
# * : 각 원소에 스칼라 값 곱함
# / : 각 원소에 스칼라 값 나눔
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [ ]:
# normalize 함수: 0~1 범위로 정규화
# 색상표의 값이 0~255라 색상 정규화 할려한거 같음
def normalize(x):
  return x / 255

# 정규화해도 size는 변함 x
t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [ ]:
# 연산시 자동으로 차원이 맟춰져서(브로드캐스트라고 함) 연산됨
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [ ]:
### 추가 코드 ###
# 아래 cell들은 다양한 브로드케스트 예시임
# 차원이 브로드케스트 될때는 각 차원의 크기가 같거나 한쪽이 1이여야함
# 차원이 브로드케스트 될때는 뒤의 차원 부터 양쪽 중 큰 값으로 됨 
# 예시 : (3 1 2 99) x (99 2 1)
# 99와 1 중 99가 크므로 4번째는 99
# 2와 2가 같으므로 3번째는 2
# 1과 99중 99가 크므로 2번째는 99
# 1번째는 3만 있으므로 그대로 3
# -> (3 99 2 99)
t11 = torch.ones(3, 1, 2, 99)
t12 = t11 * torch.rand(99, 1, 1)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

torch.Size([3, 99, 2, 99])


In [ ]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

torch.Size([4, 3, 2])


In [ ]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

torch.Size([4, 3, 2])


In [ ]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

torch.Size([4, 3, 2])


In [ ]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

torch.Size([5, 3, 4, 1])


In [ ]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

torch.Size([5, 3, 4, 1])


In [ ]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

torch.Size([3, 1, 7])


In [ ]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

torch.Size([3, 3, 3])


In [ ]:
# 브로드 케스트 할때는 차원이 같거나 1이여야함 무조건 1이거나 
# 지금은 2와 3이라서 오류
t25 = torch.empty(5, 2, 4, 1)
t26 = torch.empty(3, 1, 1)
print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [ ]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

tensor([5., 5., 5., 5.])


In [ ]:
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

tensor([25., 25., 25., 25.])


In [ ]:
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing

+ 기술적 사항
    + Tensor indexing: x[i], x[:, j], x[i, j] 등 파이썬 기본 인덱싱 가능
    + Slicing: x[start:end], 다차원은 x[start:end, start:end] 가능
    + 특정 구간/위치 값 수정 가능: x[1:4, 2] = 1
+ 기술적 고찰
    + 인덱싱과 슬라이싱을 활용하면 필요한 부분만 쉽게 추출하거나 수정할 수 있을 것 같다.
    + 다차원 Tensor에서도 직관적으로 범위를 지정할 수 있어 한번에 편리하게 수정할 수 있을 것 같다.


In [ ]:
# 2차원 텐서 생성
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [ ]:
# 슬라이싱 하는법
# [n:] = n부터 끝까지 자르기
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [ ]:
# 원하는 부분 값 변경
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [ ]:
# 원하는 부분 출력
print(y[1:4, 1:4])

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [ ]:
# 원하는 부분 출력
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
# 원하는 부분 값 변경
z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping

+ 기술적 사항
    + view(shape): Tensor 크기 재배열
    + reshape(shape): Tensor 크기 재배열
    + squeeze(dim): 크기 1인 차원 제거
    + unsqueeze(dim): 새로운 차원 추가
    + flatten(start_dim, end_dim): Tensor를 1차원으로 펼치거나 특정 차원만 펼침
    + permute(dims): 차원 순서를 원하는 대로 변경
    + transpose(dim0, dim1): 두 차원 위치 교환
    + t(_: 2D Tensor 전치(transpose)
+ 기술적 고찰
    + view와 reshape를 사용하여 Tensor를 원하는 모양으로 변경 할 수 있을 것 같다.
    + squeeze/unsqueeze는 차원 관리할 때 자주 쓰일 것 같다
    + permute와 transpose는 계산시 차원 순서를 바꿔야 할 때 잘 사용될 것 같다.

In [ ]:
# view, reshape : 텐서의 모양 변경
# 각각 (3 2), (1 6), (2 4), (2 3)으로 변경
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
# squeeze : 차원이 1인 부분 제거
# dim으로 적용할 차원 선택 가능
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)
# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [ ]:
# unsqueeze: 차원 늘리기
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [ ]:

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)
print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [ ]:

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)
t17 = torch.flatten(t15, start_dim=1)
print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [ ]:

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [ ]:

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat

+ 기술적 사항
    + torch.cat(tensors, dim): 여러 Tensor를 특정 차원을 기준으로 이어붙임
    + dim=0: 새로운 행(위아래 방향)으로 연결
    + dim=1: 열(좌우 방향)로 연결
    + dim=2: 3차원 이상에서 마지막 축을 기준으로 연결
+ 기술적 고찰
    + cat은 Tensor를 이어붙일 때 차원 크기가 맞아야 해서 shape 설계가 중요할 것 같다.
    + 특히 다차원 텐서는 dim 선택에 따라 연산이 달라지므로 주의해야할 것 같다.

In [17]:
# 3차원 텐서 cat (dim=1)
# 2번째 차원 크기 = 1+3+2 = 6
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


In [18]:
# 1차원 텐서 cat (dim=0)
# 길이 = 3+5 = 8
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [19]:
# 2차원 텐서간 병합
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# dim=0 -> row 증가
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())
print(t10)
# dim=1 -> column 증가
t11 = torch.cat((t8, t9), dim=1)
print(t11.size())
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [20]:
# 여러 개 cat 가능
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

# dim=0 -> 2+2+2 = 행 6개
t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# dim=1 -> 3+3+3 = 열 9개
t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [21]:
# dim 1, 2, 3
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

# dim=0: 1번째 차원 증가
t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# dim=1: 2번째 차원 증가
t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# dim=2: 3번째 차원 증가
t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking

+ 기술적 사항
    + torch.stack(tensors, dim): 새로운 차원을 추가해서 텐서들을 쌓음
    + torch.cat(tensors, dim): 기존 차원 기준으로 텐서를 이어붙임
    + unsqueeze(dim): 특정 위치에 차원 하나 추가 → cat+unsqueeze = stack
+ 기술적 고찰
    + stack은 새로운 차원을 추가해 데이터를 묶을 때 직관적일 것 같다.
    + unsqueeze로 추가한 차원을 기준으로 cat 하면 stack과 같은 효과를 낼 수 있다.


In [22]:
# stack과 cat의 차이
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

#stack은 맨 앞에 새로운 차원을 생성하여 만듬
t3 = torch.stack([t1, t2], dim=0)
# cat은 기존의 차원에 연결함
# unsqueeze로 앞에 차원 하나 더 만들어서 연결하니 결과 동일
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

# dim=1 새로운 차원을 생성할 위치 지정
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [23]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])
print(t9.size(), t10.size())

# dim=0이면 (1 3) + (1 3)과 같음
t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

# dim=0이면 (3 1) + (3 1)과 같음
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


In [32]:
### 추가 코드 ###
# cat은 선택한 차원만 맞으면 되지만
# stack은 두 차원이 완전히 동일해야함 아니면 애러남
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9]])

print(torch.cat([t1, t2], dim=0))
print(torch.stack([t1, t2], dim=0)) # 에러

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [1, 3] at entry 1

# n_tensor_vstack_hstack

+ 기술적 사항
    + torch.vstack(tensors): 텐서들을 세로 방향(행 기준, dim=0)으로 쌓음
    + torch.hstack(tensors): 텐서들을 가로 방향(열 기준, dim=1)으로 쌓음
    + vstack/hstack은 cat을 dim=0, dim=1로 사용하는 것과 동일
+ 기술적 고찰
    + vstack, hstack은 Vertical, Horizontal로 생각하면 쉽게 구분할 수 있다.
    + 텐서끼리 가로, 세로로 합쳐야 할때 사용하면 좋을 것 같다.
    + cat으로도 가능하지만 vstack/hstack을 쓰면 사용 목적이 잘 들어난다.

In [25]:
# 1차원 벡터를 세로 방향으로 연결
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [26]:
# 2차원 벡터를 세로 방향으로 연결
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
print(t6)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [27]:
# 3D 텐서 (2 2 3)
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# 3D 텐서 (2 2 3)
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

# vstack -> 세로로 연결함
t9 = torch.vstack([t7, t8])
print(t9.shape)
print(t9)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [28]:
# 1차원 벡터를 가로 방향 연결
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [29]:
# 2차원 벡터를 가로 방향 연결
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [30]:
# 3D 텐서 (2 2 3)
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# 3D 텐서 (2 2 3)
t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

# hstack -> 가로로 연결함
t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 숙제 후기

이번 과제를 진행하면서 단순히 주어진 코드만 따라 적는 것이 아니라, 실제로 코드를 실행해보고 그 결과를 확인하는 과정에서 많은 것을 배울 수 있었다. 특히 텐서의 사용 방법이나 텐서와 관련된 연산들을 이해할 수 있었으며, 배우는 과정에서의 궁금증도 코드를 추가로 작성하여 테스트 해보면서 더 많은 공부가 되었다. 텐서가 공학수학에서의 행렬의 개념과 비슷하여 잘 이해할 수 있었으며 재미있었다.

또한 코드를 모두 작성하고 다시 한번 내가 작성한 코드를 보며 고찰을 작성하였는데, 처음 코드를 작성할때와는 다른 시각으로 볼수 있어서 좋았다. 텐서 초기화 시에 각 차원의 원소 개수가 동일해야 한다는 점이나 requires_grad의 의미와 같은 세부적인 부분을 스스로 정리해 보니, 그냥 코드를 따라 치는 것보다 훨씬 깊이 있는 이해로 이어졌다.

과정을 진행하면서 느낀 점은, 프로그래밍 공부는 단순히 교재나 예시 코드를 보는 것만으로는 부족하고, 작은 코드라도 내가 직접 작성해보고, 예상과 다른 결과가 나오면 그 이유를 찾아보는 과정 학습에 매우 도움이 된다는 점이다. 특히 PyTorch와 같은 딥러닝 라이브러리는 기능이 매우 많고 이러한 기능을 아는지 모르는지가 코딩의 효율에 매우 큰 영향을 주기 때문에 열심히 공부해야겠다는 생각이 들었다. 

In [31]:
print("home work end 2020136031 KimJusang :)")

home work end 2020136031 KimJusang :)
